# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

     dependencies = [
          ('file_repository', '0002_auto_20160315_0601'),
     ]

     operations = [
          migrations.AddField(
                model_name='inode',
                name='rootname',
                field=models.CharField(default='', max_length=10),
          ),
     ]
