# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0003_inode_rootname'),
    ]

    operations = [
        migrations.AddField(
            model_name='inode',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='parentinodes', to='file_repository.Inode'),
        ),
        migrations.AlterField(
            model_name='inode',
            name='inodes',
            field=models.ManyToManyField(related_name='subinodes', to='file_repository.Inode'),
        ),
    ]
