# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_repository', '0005_auto_20160318_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inode',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentinodes', to='file_repository.Inode'),
        ),
    ]
